name: 05 - 2 - Event Filters and Activity Types
on:
  pull-request:
    types:
      - closed
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Event filter explained
        run: echo 'Running whenever a PR is closed'
