name: 07 - Using Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

run-name: 07 - Using Expressions | DEBUG - <'ON' if the debug input is true, 'OFF' otherwise>

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print start-up data
        if: ${{ inputs.debug && true || false}}
        run: |
          echo "Triggered by: ${{ github.event }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"