name: 07 - Using Expressions
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print start-up data
        if: ${{ inputs.debug && true || false }}   # executes if input is true
        run: |
          echo "Triggered by: ${{ github.event }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"