name: 07 - Using Expressions
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: [debug] Print start-up data
        if: ${{ inputs.debug = 'true' }}
        run: |
          echo "Triggered by: ${{ github.event }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"