name: 07 - Using Expressions
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.debug == 'true' }}
        name: [debug] Print start-up data
        run: |
          echo "Triggered by: ${{ github.event }}"
          echo "Branch: ${{ github.ref	}}"
          echo "Commit SHA: ${{ github.sha	}}"
          echo "Runner OS: ${{ runner.os	}}"